### ISSUE TITLE
Page empty

### ISSUE THREAD

**Issue by zhouhao27** [aspendigital/docker-octobercms#21]
Here is my **docker-compose.yml**:

```
version: '3.3'
services:
  web:
    image: aspendigital/octobercms
    restart: always
    container_name: octobermovies
    ports:
      - 8800:80
    volumes:
      - ./storage:/var/www/html/storage
      - ./plugins:/var/www/html/plugins
      - ./themes:/var/www/html/themes
```

The page will be blank.

Then I change my **docker-compose.yml** to this:

```
version: '3.3'
services:
  web:
    image: aspendigital/octobercms
    restart: always
    container_name: octobermovies
    ports:
      - 8800:80
    volumes:
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
      - ./storage/database.sqlite:/var/www/html/storage/database.sqlite
      - ./plugins/myplugin:/var/www/html/plugins/myplugin
      - ./themes/newtheme:/var/www/html/themes/newtheme
```

It works then.

I noticed it's because the folder will be removed when the folder in host is mapped to a folder in container. Is there a way to keep the data in container? Thanks.
