### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by edDimensi** [aspendigital/docker-octobercms#8]
Try use you docker image for start working with octobercms.
Use docker-compose.yml from readme.md.
```yml
#docker-compose.yml
version: '3'
services:
  web:
    image: aspendigital/octobercms:build.431-php7.0-apache
    ports:
      - 127.0.0.1:4000:80
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql #DB_HOST should match the service name of the database container
      DB_DATABASE: october
      DB_USERNAME: october
      DB_PASSWORD: Y5gExv_p
    volumes:
      - $PWD/october:/var/www/html/
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: october
      MYSQL_USER: october
      MYSQL_PASSWORD: Y5gExv_p
```
I got success install containers and october not installed. 
```bash
-rw-r--r--  1 dimensi dimensi  631 feb  8 03:02 docker-compose.yml
drwxrwxrwx  2 dimensi dimensi 4096 feb  8 02:55 october
```
October dir is empty. What i do wrong?
I connect to container and cd to /var/www/html and this dir is empty too.

**Comment by albrechtsimon** [comment]
The OctoberCMS files get added to the image during build. See the Dockerfile. Volume mounts are created when launching a container. As far as I know, mounts are directed from host system towards container system, which in turn means that if your directory on the host system is empty when it gets mounted, it will be empty within your container as well.

**Comment by petehalverson** [comment]
@albrechtsimon, that's correct. The October CMS files exist in the image. I typically create volume bind mounts for those folders I'm working on. Here's an example from a typical project:

```yaml
#docker-compose.yml
version: '2.3'
services:
  web:
    image: aspendigital/octobercms:latest
    init: true
    ports:
      - 80:80
    environment:
      - TZ=${TZ:-America/Denver}
    volumes:
      # A local `.env` is not required but expected if you wish to override config values - see README.md
      # - ./.env:/var/www/html/.env

      - ./plugins:/var/www/html/plugins
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs

      # Uncomment the line below for a persistent local database
      # - ./storage/database.sqlite:/var/www/html/storage/database.sqlite

      - ./themes:/var/www/html/themes
```

@edDimensi, I noticed your example uses docker-compose version 3 which handles volumes differently. I have stuck with version 2.x as it matches my workflow. See more about the difference: https://github.com/docker/compose/issues/4675
